### ISSUE TITLE
Installing the addon for v7 (next) warning...

### ISSUE THREAD

**Issue by MMT-LD** [storybookjs/addon-styling#11]
When installing the version 'next' a warning is printed in storybook v7.

`You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0`

I think this comes from the exported `preset.js` file.

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#config-preset-entry-replaced-with-previewannotations

Thought i would share.

**Comment by Integrayshaun** [comment]
Thank you @MMT-LD! I'm going to work on getting this cleaned up over the next week or so

**Comment by Integrayshaun** [comment]
Hey @MMT-LD 

I've released version 1.0.0 with the official launch of Storybook 7.0.0. This resolves the deprecation warning 🎉
