### ISSUE TITLE
[Bug] withThemeFromDataAttribute is not found

### ISSUE THREAD

**Issue by 0r0loo** [storybookjs/addon-styling#13]
### Describe the bug

https://storybook.js.org/recipes/tailwindcss#tailwindcss

```js
// .storybook/preview.js
import { withThemeByDataAttribute } from '@storybook/addon-styling';

/* snipped for brevity */

export const decorators = [
  withThemeFromDataAttribute({
    themes: {
      light: 'light',
      dark: 'dark',
    },
    defaultTheme: 'light',
    attributeName: 'data-mode',
  }),
];
```

withThemeFromDataAttribute is not found....

https://github.com/storybookjs/addon-styling/blob/main/docs/api.md#withthemebydataattribute

Shouldn't we change withThemeFromDataAttribute => withThemeByDataAttribute?

cf) I don't speak English very well. 🥲ㅠㅠ

### Steps to reproduce the behavior

https://storybook.js.org/recipes/tailwindcss#tailwindcss to follow

### Environment

 - OS: Mac
 - Node.js version: v18.12
 - NPM version: yarn 1.22.19.  npm 8.19.2
 - Browser (if applicable):  chrome
 - Browser version (if applicable): 111.0.5563.64
 - Device (if applicable):

**Comment by Integrayshaun** [comment]
Hi @0r0loo 

Oh no! I'm sorry, yes, the correct code would be

```js
// .storybook/preview.js
import { withThemeByDataAttribute } from '@storybook/addon-styling';

/* snipped for brevity */

export const decorators = [
  withThemeByDataAttribute({
    themes: {
      light: 'light',
      dark: 'dark',
    },
    defaultTheme: 'light',
    attributeName: 'data-mode',
  }),
];
```

I'll correct that on our website now

**Comment by Integrayshaun** [comment]
This should be rebuilt and deployed shortly 😁 

Apologies 😓
