### ISSUE TITLE
[Feature Request] Support for BEM

### ISSUE THREAD

**Issue by GabrielAPineiro** [storybookjs/addon-styling#18]
### Describe the bug

I've tried creating themes based on BEM modifiers, but one theme caused the removal of the base class on the other theme
![image](https://user-images.githubusercontent.com/104081429/228212792-501ca66d-02c1-49ca-83ba-621fa91ea387.png)

After applying the right theme (themeName === selectedThemeName)
![image](https://user-images.githubusercontent.com/104081429/228213419-effde029-adf1-4761-9cc2-37e9aff93af5.png)

Then going through the second theme (visualTrialLight)
![image](https://user-images.githubusercontent.com/104081429/228213556-fdbf06ed-31d8-47b1-9117-a7fc2a7d5a50.png)

### Steps to reproduce the behavior

1. Have two themes which use BEM modifiers with a common base class
2. Apply one theme in one story and the other theme in another story
3. Check applied classes, one of the stories will only have the class with the modifier and will miss the base class

**Comment by Integrayshaun** [comment]
Hey @GabrielAPineiro 👋 

I've addressed this for version 1.0.0 🎉
