### ISSUE TITLE
[Feature Request] Allow users to opt out of `resolve-url-loader` when using sass implementation

### ISSUE THREAD

**Issue by Eleeleth** [storybookjs/addon-styling#19]
In attempting to migrate over from `@storybook/preset-scss`, I wasn't able to get this loading without installing `resolve-url-loader`, which is added 100% of the time with no option to configure this.

Another option that would work for my use case would be to allow options passed into the loader. Currently it appears they're passed into the function, but not the loader settings.

**Comment by Eleeleth** [comment]
After seeing the comment here: https://github.com/storybookjs/addon-styling/issues/64#issuecomment-1638731705
I realized I could use the advice there to work around my issue for the moment, I was unaware of `options.scssBuildRule` and that was enough to solve my problem.

I'm okay with closing the issue, but I'll leave that up to y'all in case you want to keep it around for whatever reason.

**Comment by Integrayshaun** [comment]
Hey @Eleeleth I think that we'll have something that will work for you in version 2.0 :)
While the API for the addon is pretty simplified it leaves a lot of cases like yours out

**Comment by Integrayshaun** [comment]
Hey @Eleeleth 

I ended up splitting up some of the functionality of addon-styling into two addons.

If you'd like, you can migrate over to the new [`@storybook/addon-styling-webpack`](https://github.com/storybookjs/addon-styling-webpack) that has a much more open API.

I don't currently have a migration script between the two but if you run the command below and follow the prompts, you should be able to get set up and then you can remove `@storybook/addon-styling`
