### ISSUE TITLE
[Feature request] Is it possible to get the "theming" parameter outside of stories?

### ISSUE THREAD

**Issue by PetterRuud** [storybookjs/addon-styling#20]
I have a react component file where I use the <ColorPalette /> from @storybook/addon-docs.
This file is then imported into a mdx file.
Would be handy to get the theming parameter/theme global so I can swap between my light and dark theme.

Something like this, but the tsx file doesnt have the context of storybook, so this wont work.

palette.tsx
import { useParameter } from '@storybook/api';
const theme = useParameter('theming', 'light');

useParameter/useGlobals just works in the context of a story/addon if I'm mistaken.

other idea would be to have is sent to the component via the mdx file.
<Palette theme={theme} />

**Comment by Integrayshaun** [comment]
Hey @PetterRuud 

Apologies for the super late reply! I've had my head stuck in a lot of different rabbit holes and your request got buried.

Unfortunately, making a user's custom theme to our out-of-the-box doc components gets risky as we can't guarantee that they will look right or have accessible color contrast.

In cases like this, i'd recommend creating a custom docs template that can use your theme by creating components that wrap our existing doc blocks and provide the custom styles that you'd like.

This is something that has come up a few times now and i'll perhaps try to throw together an example repo sometime soon.

I hope that this helps.

**Comment by PetterRuud** [comment]
> I have a react component file where I use the from @storybook/addon-docs. This file is then imported into a mdx file. Would be handy to get the theming parameter/theme global so I can swap between my light and dark theme.
> 
> Something like this, but the tsx file doesnt have the context of storybook, so this wont work.
> 
> palette.tsx import { useParameter } from '@storybook/api'; const theme = useParameter('theming', 'light');
> 
> useParameter/useGlobals just works in the context of a story/addon if I'm mistaken.
> 
> other idea would be to have is sent to the component via the mdx file.

Thanks for the answer.
