### ISSUE TITLE
[Bug] TS Tailwindcss config not getting picked up

### ISSUE THREAD

**Issue by felix-schaipp** [storybookjs/addon-styling#26]
### Describe the bug

If one uses the newly introduced option by [tailwindcss to write the config as esm/ts](https://tailwindcss.com/blog/tailwindcss-v3-3#esm-and-typescript-support) it will not be picked up by the addon-styling even if the css file is imported.

### Steps to reproduce the behavior

1. Install latest storybook version
2. Install taliwind with `--esm` or `--ts` flag
```typescript
import type { Config } from "tailwindcss"

const config: Config = {
  content: ["./src/**/*.tsx"],
  darkMode: "class",
  theme: {
    extend: {},
  },
  plugins: [],
}

export default config
```
3. Add the addon configuration in `main.ts` 
```typescript
import type { StorybookConfig } from "@storybook/react-vite"
import { mergeConfig } from "vite"
const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(ts|tsx)"],
  addons: [
    "storybook-dark-mode",
    "@storybook/addon-a11y",
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    {
      name: "@storybook/addon-styling",
      options: {
        postCss: true,
      },
    },
  ],
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
  typescript: {
    check: true,
    skipBabel: true,
  },
  async viteFinal(config) {
    return mergeConfig(config, {
      optimizeDeps: {
        include: ["storybook-dark-mode"],
      },
    })
  },
  docs: {
    autodocs: true,
  },
}
export default config

```
4. Import the css file in `preview.ts`
```typescript
import { withThemeByClassName } from "@storybook/addon-styling"
import "../src/index.css"
export const decorators = [
  withThemeByClassName({
    themes: {
      light: "",
      dark: "dark",
    },
    defaultTheme: "light",
  }),
]
```

### Expected behavior

New tailwind config extension `.ts` works the same as old ones like `.cjs` or `.js`

### Screenshots and/or logs

If applicable, add screenshots and/or logs to help explain your problem.

### Environment

 - OS: MacOS Monterey (12.6.3)
 - Node.js version: v19.2.0
 - PNPM version: 7.26.2
 - NPM version: 8.19.3
 - Browser: Chrome
 - Browser version:  110.0.5481.100

### Additional context

Starting with a `tailwind.config.ts` the console output shows missing config data.
<img width="627" alt="Screenshot 2023-04-13 at 15 51 41" src="https://user-images.githubusercontent.com/76478694/231780256-4d33ce44-fda6-48ee-842b-07e659f7c273.png">

**Comment by Integrayshaun** [comment]
Hey @felix-schaipp it looks like your tailwind config is being picked up but you haven't set the content option that tells tailwind what files to look Tailwind classes in.

For a react vite project you'd want something like this:

```ts
import type { Config } from 'tailwindcss'

export default {
  // Look in files that match these patterns for tailwind classes
  // to only build the css you use
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
} satisfies Config
```

**Comment by Integrayshaun** [comment]
I'm going to close this issue for now since it's been a month since the last comment.

Happy to reopen if it's still a problem 😁
