### ISSUE TITLE
[Bug] Imports in the Writing a Custom Decorator code examples in the docs do not work

### ISSUE THREAD

**Issue by RegisFrey** [storybookjs/addon-styling#29]
### Describe the bug

Imports in the [Writing a Custom Decorator](https://github.com/storybookjs/addon-styling/blob/v1.0.1/docs/api.md#writing-a-custom-decorator) code examples in the docs are invalid (using v1.0.1),
Typescript warns there are no matching exports:
`Module '"@storybook/addon-styling"' has no exported member 'initializeThemeState'. Did you mean to use 'import initializeThemeState from "@storybook/addon-styling"' instead?ts(2614)`

[pluckThemeFromContext](https://github.com/storybookjs/addon-styling/blob/v1.0.1/docs/api.md#pluckthemefromcontext)
`import { pluckThemeFromContext } from "@storybook/addon-styling";`

[useThemeParameters](https://github.com/storybookjs/addon-styling/blob/v1.0.1/docs/api.md#usethemeparameters)
`import { useThemeParameters } from "@storybook/addon-styling";`

(aside: [initializeThemeState](https://github.com/storybookjs/addon-styling/blob/v1.0.1/docs/api.md#initializethemestate) doesn't have an import line like the previous 2, should it?)

### Workaround:

The code does export a `DecoratorHelpers` object that contains those functions, so changing the import to the following removes the import error:
```ts
import { DecoratorHelpers } from '@storybook/addon-styling';
const { initializeThemeState, pluckThemeFromContext, useThemeParameters } = DecoratorHelpers;
```

**Comment by Integrayshaun** [comment]
Hey @RegisFrey 👋 

Thank you for that catch! you're 100% correct.

Any chance you'd be willing to put together a small PR with the fix? It's just me maintaining this right now and I have a bunch of other stuff on my plate right now 😅 I'd really appreciate it

**Comment by RegisFrey** [comment]
Put up a PR https://github.com/storybookjs/addon-styling/pull/30
