### ISSUE TITLE
[Bug] 'audit' reports critical/high vulnerabilities

### ISSUE THREAD

**Issue by CHE1RON** [storybookjs/addon-styling#38]
### Describe the bug

`audit`ing project using this library gives two critical and four high vulnerabilities, see here for example:

![image](https://user-images.githubusercontent.com/122524301/237012026-2c7a0394-1edc-4076-a73b-7dd2dee3b058.png)

### Steps to reproduce the behavior

1. Install library
2. Run `npm/yarn/pnpm audit`

### Expected behavior

No reported vulnerabilities

### Environment

- OS: macOS 13.3 22E252 arm64
- Host: Mac14,2
- Node: v16.19.0

**Comment by Integrayshaun** [comment]
Hi @CHE1RON 

What version of the addon are you using? I wasn't able to reproduce this with the latest version, `1.0.6`

**Comment by CHE1RON** [comment]
Hey there @Integrayshaun, same as you (latest version, as far as I can see) 🤔 strange ..
