### ISSUE TITLE
[Bug] React Native + Styled Components unable to resolve addon-styling

### ISSUE THREAD

**Issue by guidovdijk** [storybookjs/addon-styling#40]
### Describe the bug
I am trying to set up Storybook with Styled Components for React Native using `Expo v48`, but I get this error every time I try to run the Expo Go app to view my stories:

```
Unable to resolve "@storybook/addon-styling/register" from ".storybook\storybook.requires.js"
```

I followed this tutorial: https://storybook.js.org/recipes/styled-components

**I use the following versions of the dependencies:**

- "styled-components": "5.3.10"
- "expo": "~48.0.15",
- "@types/styled-components": "^5.1.26",
- "@storybook/addon-styling": "^1.0.8",
- "@storybook/react-native": "^6.5.3",
- "@types/styled-components-react-native": "^5.2.1",
- "metro-react-native-babel-preset": "^0.76.4",

**And my .storybook folder files look like this:**

<details>
  <summary>index.js</summary>
  
  ```js
  import { getStorybookUI } from '@storybook/react-native';
  import './storybook.requires';
  
  const StorybookUIRoot = getStorybookUI({});
  
  export default StorybookUIRoot;
  ```
</details>

<details>
  <summary>main.js</summary>
  
  ```js
  // .storybook/main.js
  module.exports = {
    stories: [
      '../src/components/**/*.stories.?(ts|tsx|js|jsx)',
    ],
    addons: [
      '@storybook/addon-styling'
    ],
  };
  ```
</details>

<details>
  <summary>preview.js</summary>
  
  ```js
import { withThemeFromJSXProvider } from '@storybook/addon-styling';
import { ThemeProvider } from 'styled-components/native';

import { theme, themeDark } from '../src/theme';


export const decorators = [
    withThemeFromJSXProvider({
      themes: {
        light: theme,
        dark: themeDark
      },
      defaultTheme: 'light',
      Provider: ThemeProvider,
    }
)];


  ```
</details>

**The metro file looks like this:**
<details>
  <summary>metro.config.js</summary>
  
  ```js
  // Learn more https://docs.expo.io/guides/customizing-metro
  const { getDefaultConfig } = require('expo/metro-config')
  
  const config = getDefaultConfig(__dirname)
  
  config.watchFolders = ['.storybook', __dirname]
  
  config.resolver.resolverMainFields = ['sbmodern', ...config.resolver.resolverMainFields]
  
  module.exports = config
  ```
</details>

**The story looks like this:**

<details>
  <summary>button.stories.tsx</summary>
  
  ```js
  import {
    View
  } from 'react-native'
  
  import Button, { ButtonProps } from '.'
  
  export default {
    title: 'Atoms/Button',
    component: Button,
  }
  
  export const Basic = (args: ButtonProps) => (
    <View>
      <Button>{args.children}</Button>
    </View>
  )
  
  Basic.args = {
    children: 'Hello World',
    variation: 'primary',
  }
  ```
</details>

### Steps to reproduce the behavior

1. Create an Expo app
2. Setup Storybook and Styled Components
3. Use the Addon Styling to use the Styled Components theme
4. Run the app: `sb-rn-get-stories && cross-env STORYBOOK_ENABLED='true' expo start --android`

### Expected behavior

The storybook environment starts up with the Addon Styling adding the theme to all the stories.

### Screenshots and/or logs

![image](https://github.com/storybookjs/addon-styling/assets/32161849/42553289-b93d-4735-a527-604c8c79c948)

### Environment

 - OS: Windows 11
 - Node.js version: 16.13.2
 - NPM version: 8.1.2
 - Device: Emulator, Pixel pro 6 - API level 33

**Comment by Integrayshaun** [comment]
Hey @guidovdijk 👋 

`@storybook/addon-styling` >= 1.0.0 doesn't work with Storybook v6. You'll need to downgrade to version 0.3.2.

@dannyhw does `@storybook/react-native@6.5.x` only accept register scripts? This addon works through a `preset.js` script instead

**Comment by dannyhw** [comment]
@Integrayshaun presets aren't implemented in the same way. It's possible to use them but they don't work by default. For example addon actions works but only as a special case.

This is something that I'm planning to revisit but its one of many things on the list 😅 .

to use styled-components it would probably be simpler to just add a global decorator with the provider or to wrap the entire app in the provider (probably the better option).

**Comment by guidovdijk** [comment]
Ah that's a shame. Yeah I will just wrap it.
For anyone that has the same problem as me this is how you can wrap your stories.

_The annoying part is that you need to switch between `light` and `dark` theme through your device settings_

<details>
  <summary>WrapperDecorator.tsx</summary>
  
  ```js
import React from 'react';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { ThemeProvider } from 'styled-components/native';

import { theme, themeDark } from '../src/theme/index';
import { useColorScheme } from 'react-native';

const withWrapper = (Story: any) => {
    const themeType = useColorScheme()
    const activeTheme = themeType === 'light' ? theme : themeDark

    return (
      <SafeAreaProvider>
        <StatusBar translucent />
  
        <ThemeProvider theme={activeTheme}>
           <Story />
        </ThemeProvider>
      </SafeAreaProvider>
    )
}

export default withWrapper
  ```
</details>

<details>
  <summary>preview.ts</summary>
  
  ```js
import type { DecoratorFunction, Parameters } from '@storybook/types';

import withWrapperDecorator from "./withWrapperDecorator";

export const decorators: DecoratorFunction[] = [
    (StoryFn) => (
       withWrapperDecorator(StoryFn)
    )
]
  ```
</details>
