### ISSUE TITLE
[Bug] - context.globals.theme is empty string when default

### ISSUE THREAD

**Issue by jeremydrichardson** [storybookjs/addon-styling#45]
### Describe the bug

When using `withThemeFromJSXProvider`, attempting to grab the current theme from the context using the story `render` function, the `context.globals.theme` is an empty string when set to the default theme.

```typescript
export const Primary: Story = {
  render: (args, context) => {
    console.log("context", context)
    return <Box>some text</Box>;
  }
}
```

```typescript
export const decorators: Decorator[] = [
  withThemeFromJSXProvider({
    themes,
    Provider: ThemeProvider,
    defaultTheme: 'v3',
  }),
];
```

```json
{
    "backgrounds": null,
    "measureEnabled": false,
    "outline": false,
    "theme": ""
}
```

### Expected behavior

`context.globals.theme` should always represent the current theme name regardless of whether it is the default or not.

**Comment by Integrayshaun** [comment]
@jeremydrichardson! Oh no, that's odd. 

Can you provide me with a reproduction repo for this problem?

**Comment by jeremydrichardson** [comment]
I can't with the project I'm working on, it's an internal project.

I'll see if I can spin up a demo version that demonstrates the issue.

**Comment by jeremydrichardson** [comment]
For anyone else who find this, my workaround was to set a global for `theme` and set it to what I wanted the default theme to be. I used a variable so I could make sure the `withThemeFromJSXProvider` was the same as the global I set.

```typescript
const defaultTheme = 'mytheme';

export const globals = {
  themes,
  theme: defaultTheme,
};

export const decorators: Decorator[] = [
  withThemeFromJSXProvider({
    themes,
    Provider: ThemeProvider,
    defaultTheme: defaultTheme,
  }),
];
```

**Comment by Integrayshaun** [comment]
Hey @jeremydrichardson 👋 

Were you ever able to reproduce this in another project? I still haven't come across this.

Also, what version of the addon are you using?
