### ISSUE TITLE
How to set localIdentName to cssModules using PostCSS?

### ISSUE THREAD

**Issue by equinusocio** [storybookjs/addon-styling#48]
Hello just trying to find a way to set a custom `localIdentName` for CSSModules using PostCSS. Can't find an example from the doc. My config is:

```js
{
  name: '@storybook/addon-styling',
  options: {
    cssModules: true,
    postCss: {
      implementation: require('postcss'),
    },
  },
},
```

**Comment by Integrayshaun** [comment]
Hey @equinusocio 👋 

Sorry about that! I'll make a ticket to get that area of the docs fleshed out. To set your `localIdentName` you can set `cssModules` to an object like so:

```js
{
  name: '@storybook/addon-styling',
  options: {
    cssModules: {
      auto: true,
      localIdentName: '[path][name]__[local]--[hash:base64:5]',
    },
    postCss: {
      implementation: require('postcss'),
    },
  },
},
```

Basically, the `cssModules` option in the addon will accept anything that webpack's `css-loader` does in the [modules property](https://www.npmjs.com/package/css-loader#modules)

**Comment by equinusocio** [comment]
Thanks for the fast support. It could be useful to update the cssModules section with this additional info!
