### ISSUE TITLE
[Bug] Can't install if using React +18

### ISSUE THREAD

**Issue by racsogrok** [storybookjs/addon-styling#5]
### Describe the bug

I'm looking to use this addon for a component library that uses React +18, but it looks like the [peer dependencies specify that React must be in range `^16.8.0 || ^17.0.0`](https://github.com/storybookjs/addon-styling/blob/9823a0c69a51b90be43e48171a000ff6c6ebcf2a/package.json#L74). Anyway we can add support for `^18.0.0` as well?

### Steps to reproduce the behavior

1. Create a component library that uses react version >= 18
2. Try to install the add-on via `npm install -D @storybook/addon-styling`

### Screenshots

<img width="724" alt="image" src="https://user-images.githubusercontent.com/117498778/223620015-091d07c3-c602-4d5d-8979-e3c824b8d80b.png">

### Environment

 - OS: macOS
 - Node.js version: v16.19.1
 - NPM version: 8.19.3

**Comment by Integrayshaun** [comment]
Hey @racsogrok of course! Apologies, that was an oversight on my part 😓

I'll add this to my list of things to tackle today. Stay tuned 📻

**Comment by Integrayshaun** [comment]
@racsogrok Version 0.3.1 is just publishing now 🎉 That should get you going with React 18 😁

Let me know if you have any trouble and i'll take an additional stab at it
