### ISSUE TITLE
[Bug] [PostCSS] css-modules doesn't resolve

### ISSUE THREAD

**Issue by kir-rik** [storybookjs/addon-styling#53]
### Documentation suggestion

Migration from storybook 6 to 7 and @storybook/addon-postcss to @storybook/addon-styling can be challenging. It would be great to have more documentation, especially for cssLoaderOptions. Narrowing types on options also would be very helpful

After some amount of tries I came to this migration for my case

Old config:
```
{
      name: '@storybook/addon-postcss',
      options: {
        styleLoaderOptions: {},
        cssLoaderOptions: {
          importLoaders: 1,
          modules: {
            localIdentName: '[path][name]__[local]',
          },
        },
        postcssLoaderOptions: {
          postcssOptions: {
            config: path.resolve(__dirname, '..', 'postcss.config.js'),
          },
        },
      },
}
```

new config
```
{
      name: '@storybook/addon-styling',
      options: {
        cssModules: {
          localIdentName: '[path][name]__[local]',
        },
        postCss: {
          implementation: require('postcss'),
        },
      },
}
```

**Comment by Integrayshaun** [comment]
Hey @kir-rik 👋 

Thank you for sharing this! It sounds like I should make a migration guide for `@storybook/addon-postcss` to `@storybook/addon-styling`

Just to clarify, does your new config work as expected now or do you need more help?

**Comment by Integrayshaun** [comment]
Hey @kir-rik, I've created a dedicated issue to write that migration guide so i'll close this issue as complete for now.

**Comment by kir-rik** [comment]
> Just to clarify, does your new config work as expected now or do you need more help

Yes, it works smoothly
