### ISSUE TITLE
Outdated @storybook/types

### ISSUE THREAD

**Issue by alanpaulprice** [storybookjs/addon-styling#55]
This package is using @storybook/types@7.0.17, which is causing the following error when upgrading to storybook@7.0.22:

Attention: The following dependencies are duplicated which might cause unexpected behavior:
@storybook/types: 7.0.17, 7.0.22
You can find more information for a given dependency by running `npm ls --depth=1 <package-name>`

Running `npm ls --depth=1 @storybook/types` produces the following output when run on a repo with storybook@7.0.22 installed:
```
├─┬ @storybook/addon-a11y@7.0.22
│ └── @storybook/types@7.0.22
├─┬ @storybook/addon-actions@7.0.22
│ └── @storybook/types@7.0.22
├─┬ @storybook/addon-interactions@7.0.22
│ └── @storybook/types@7.0.22
├─┬ @storybook/addon-links@7.0.22
│ └── @storybook/types@7.0.22
├─┬ @storybook/addon-styling@1.3.0
│ └── @storybook/types@7.0.17
├─┬ @storybook/blocks@7.0.22
│ └── @storybook/types@7.0.22
└─┬ @storybook/react@7.0.22
  └── @storybook/types@7.0.22
```
**Solution:** This package needs to be updated to use @storybook/types@7.0.22.

**Comment by ndelangen** [comment]
The package.json for this package allows for any `7.x.x` version of `@storybook/types`, you likely have a lockfile that resolves into `7.0.17`.

https://github.com/storybookjs/addon-styling/blob/main/package.json#L73-L82

Just fix this in your lockfile.
