### ISSUE TITLE
[Bug] Storybook v7 support

### ISSUE THREAD

**Issue by meza** [storybookjs/addon-styling#7]
### Describe the bug

@storybook/addon-styling has been promoted on Storybook day which was all about V7. Unfortunately the addon doesn't support V7 yet without the --legacy-peer-deps.

### Steps to reproduce the behavior

1. Try to install the addon into a project with storybook@next

### Expected behavior

A successful installation

### Screenshots and/or logs

![image](https://user-images.githubusercontent.com/211977/225363638-6b09be9d-0c1c-4848-a556-a1b21b0813d1.png)

### Environment

 - OS: Ubuntu-22.04.1
 - Node.js version: v19.7
 - NPM version: 9.6.0

**Comment by Integrayshaun** [comment]
Hey @meza I've put together a prerelease version of this package that works with 7.0 as expected. You can run `npm install -D @storybook/addon-styling@next` to install it in your project

**Comment by meza** [comment]
Amazing, thank you!

**Comment by meza** [comment]
It's kind of fitting that the V7 support was in issue #7 :D

Thanks for the speedy fix again
