### ISSUE TITLE
[Bug] `@storybook/nextjs` webpack loaders for css files get replaced by `addon-styling`.

### ISSUE THREAD

**Issue by sookmax** [storybookjs/addon-styling#70]
### Describe the bug

Hi, this issue is actually related to https://github.com/storybookjs/storybook/issues/23271. 

I was trying to find the root cause for the above issue, and I realized the webpack loaders for css files specified in `@storybook/nextjs` were replaced by that of `addon-styling`'s. This is essentially caused by the fact that `addon-styling` preset is located further behind the preset of `@storybook/nextjs` in `presets` array when `presets.apply("webpackFinal", defaultConfig, options);` is run in `code/builders/builder-webpack5/src/presets/custom-webpack-preset.ts`. I'm not really sure if the order of items in `presets` array is deterministic, but do you think there's a way to merge (rather than overwrite) previous preset's css loaders with that of `addon-styling`'s?

In the meantime, as a workaround, I also wanted to ask if the following option is absolutely necessary when using `@storybook/nextjs`:

```ts
// .storybook/main.ts
...

addons: [
   ...
    {
      name: '@storybook/addon-styling',
      options: {
        // can I comment this option out when using @storybook/nextjs?
        postCss: {
          implementation: require.resolve('postcss'),
        },
      },
    },
  ],
...
```

the `postCss` option was automatically added by running `node node_modules/@storybook/addon-styling/bin/postinstall.js`.
If it's safe to remove that option when using `@storybook/nextjs`, I'd like to use it as a workaround by not specifying any option to `@storybook/addon-styling` since then it's not going to apply the patch, which results in `@storybook/nextjs`'s css-loader being applied correctly.

#### Relevant code snippets

https://github.com/storybookjs/addon-styling/blob/79463822f1b3b9ef965b60a35312f697fffed402/src/webpack/css/webpack.ts#L68-L90

#### Screenshot of `presets` array
<img width="1470" alt="Screenshot 2023-07-13 at 7 54 45 PM" src="https://github.com/storybookjs/addon-styling/assets/71210554/098d8fbc-56a9-4fd8-b002-b9a39be4743d">

**Comment by sookmax** [comment]
@Integrayshaun It's good to hear that the option could be removed safely! May I share this info in https://github.com/storybookjs/storybook/issues/23271?

And one more request if I may, though.

Since `next.js + tailwindcss` is a very common frontend stack these days, maybe it's better _not_ to automatically include the `options.postCss` at all when running `postinstall.js` if, of course, `@storybook/nextjs` and `tailwindcss` are detected?

**Comment by Integrayshaun** [comment]
Share away 😄 

You’re absolutely right! I’m actually working on that change today

**Comment by Integrayshaun** [comment]
Hey @sookmax 👋 

Version 1.3.4 is being published now :) This should solve the bug in `postinstall.js`

Have a fantastic weekend and thank you again for filing this bug 🙏

**Comment by sookmax** [comment]
@Integrayshaun Hey that was rather dizzyingly fast 🤯. 

Thanks for the quick feedback and hey, thanks for maintaining this awesome addon, Shaun! It's much appreciated.

Cheers.
