### ISSUE TITLE
[Bug] Tailwind issues with webpack-5 configuration

### ISSUE THREAD

**Issue by qw-in** [storybookjs/addon-styling#75]
### Describe the bug

Tailwind styles are not being included

<img width="273" alt="Screenshot 2023-07-21 at 11 24 37 AM" src="https://github.com/storybookjs/addon-styling/assets/19194187/71e10844-2543-4ed0-a2d5-ea672c5fc6bd">

### Steps to reproduce the behavior

Followed the upgrade guide
- all packages to `7.1.0`
- add this addon (tried with `postCss` option too)
- import our `../app/global.css` (with `@tailwind base` etc)
- run

### Screenshots and/or logs

If applicable, add screenshots and/or logs to help explain your problem.

### Environment

 - OS: [e.g. iOS] macos
 - Node.js version: v19.6.0 
 - NPM version: yarn 3.5.0 (no pnp)

### Additional context

- custom config for remix based on `@storybook/react-webpack5`
- using `@babel/preset-typescript`

**Comment by Integrayshaun** [comment]
Hey there, @qw-in 👋 

Can you give me more information about this custom config for remix?
Addon-styling writes custom webpack rules that set up postcss to work. Based on the fact that it wasn't transformed I'd guess that the custom config you have negates the work the addon does.

Could you share a few files with me?
- main.ts
- preview.ts
- tailwind config
- postcss config

**Comment by qw-in** [comment]
> Hey there, @qw-in 👋
> 
> Can you give me more information about this custom config for remix? Addon-styling writes custom webpack rules that set up postcss to work. Based on the fact that it wasn't transformed I'd guess that the custom config you have negates the work the addon does.

Ahh, that makes sense - thanks for the clarification. We do have some webpack tweaks to make remix work - I assume these are the relevant bits:
```ts
// main.ts

const config: StorybookConfig = {
// snip
  framework: {
    name: "@storybook/react-webpack5",
    options: {},
  },
  webpackFinal: (config) => {
    config.module ||= {};
    config.module.rules = [
      {
        test: /\.server\.(tsx?|jsx?)$/,
        use: "null-loader",
      },
      ...(config.module.rules || []),
    ];

    config.resolve ||= {};
    config.resolve.alias = {
      "~": path.resolve(__dirname, "../app"),
      ...config.resolve.alias,
    };

    return config;
  },
};
```

We do have a tailwindcss config with some plugins & no postcss config. I can cut them down and build a repro if the above isn't enough 😄

**Comment by Integrayshaun** [comment]
Ahh! You’ll need to have a postcss config file too so that webpack knows how to transform the tailwind code for you.

If you copy the one from tailwind’s getting started docs that should be all you need to get going 😄 

If that doesn’t work, a repro would be awesome to help me narrow it down

**Comment by qw-in** [comment]
Sorry for the delay, can confirm that adding a `postcss.config.js` solves this:

```js
module.exports = {
  plugins: {
    tailwindcss: {},
  },
};
```
