### ISSUE TITLE
Enhancement / Question

### ISSUE THREAD

**Issue by sirjamesgray** [storybookjs/addon-styling#87]
I haven't tried it yet, but is it possible to switch the theme on all components globally? Or do I have to switch each time I go to another component? 

If the answer is no, then I'm submitting this as a request. I haven't tried it yet, but I'm not gonna install it if it doesn't have this functionality lol

**Comment by Integrayshaun** [comment]
@sirjamesgray Yes this is a global switcher. However, I'm currently working on splitting it up a bit. If you just need the theme switcher, please use `@storybook/addon-themes`
